server:
  port: 8798
  shutdown: GRACEFUL

logging:
  level:
    org.springframework.web: DEBUG
    me.elyor: DEBUG

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:member_service
    username: h2-admin
    password: h2-password

  banner:
    location: classpath:banner/test.txt

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml

app:
  cors:
    allowed-origins:
      - http://localhost:1024
    allowed-methods: GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH
  security:
    key: fxBhQvyy1CO+Ju0IQQTLXQ==
