server:
  port: 8799
  shutdown: graceful

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
      max-file-size: 10MB
      max-history: 30
  file:
    name: ./logs/member-service.log
  level:
    me.elyor: INFO
    web: INFO

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  banner:
    location: classpath:/banner/prod.txt


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml

app:
  cors:
    allowed-origins:
      - http://localhost:1024
    allowed-methods: GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH
  security:
    key: fxBhQvyy1CO+Ju0IQQTLXQ==
